on: pull_request
  push:
    branches:
      - master

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: 'Are you sure this is for master branch?'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}